ALTER DATABASE OPEN;


-- CREACION Y CONFIGURACION DEL USUARIO 1
DROP USER OYARZUN_DB CASCADE;

CREATE USER OYARZUN_DB IDENTIFIED BY DUOC;
ALTER USER OYARZUN_DB DEFAULT TABLESPACE USERS;
ALTER USER OYARZUN_DB TEMPORARY TABLESPACE TEMP;
ALTER USER OYARZUN_DB QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO OYARZUN_DB;
GRANT CREATE TABLE TO OYARZUN_DB;
GRANT CREATE SEQUENCE TO OYARZUN_DB;
GRANT CREATE TRIGGER TO OYARZUN_DB;
GRANT CREATE ANY SYNONYM TO OYARZUN_DB;


-- CREACION Y CONFIGURACION DEL USUARIO 2
DROP USER HENRIQUEZ_DEV CASCADE;

CREATE USER HENRIQUEZ_DEV IDENTIFIED BY DUOC;
ALTER USER HENRIQUEZ_DEV DEFAULT TABLESPACE USERS;
ALTER USER HENRIQUEZ_DEV TEMPORARY TABLESPACE TEMP;
ALTER USER HENRIQUEZ_DEV QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO HENRIQUEZ_DEV;
GRANT CREATE VIEW TO HENRIQUEZ_DEV;
GRANT SELECT ON OYARZUN_DB.ASESOR TO HENRIQUEZ_DEV WITH GRANT OPTION;
GRANT SELECT ON OYARZUN_DB.PROFESION TO HENRIQUEZ_DEV WITH GRANT OPTION;
GRANT SELECT ON OYARZUN_DB.AFP TO HENRIQUEZ_DEV WITH GRANT OPTION;
GRANT SELECT ON OYARZUN_DB.PROYECTO TO HENRIQUEZ_DEV WITH GRANT OPTION;

CREATE OR REPLACE SYNONYM HENRIQUEZ_DEV.ASESOR
                     FOR OYARZUN_DB.ASESOR;
CREATE OR REPLACE SYNONYM HENRIQUEZ_DEV.PROFESION
                     FOR OYARZUN_DB.PROFESION;
CREATE OR REPLACE SYNONYM HENRIQUEZ_DEV.AFP
                     FOR OYARZUN_DB.AFP;
CREATE OR REPLACE SYNONYM HENRIQUEZ_DEV.PROYECTO
                     FOR OYARZUN_DB.PROYECTO;

-- CREACION DE VISTA EN BASE A CONSULTA EJECUTADA POR EL USUARIO 2
CREATE OR REPLACE VIEW V_PAGOS_ASESOR AS
SELECT TO_CHAR(ASE.NUMRUN_ASE, '00G000G000')||'-'||DVRUN_ASE RUN_ASESOR,
       APPATERNO||' '||SUBSTR(APMATERNO, 1, 1)||'. '||NOMBRE NOMBRE_ASESOR,
       TO_CHAR(SUELDO, '$9G999G999') SUELDO_ASESOR,
       NOMBRE_PROFESION PROFESION,
       NOMBRE_AFP AFP,
       COUNT(ASE.NUMRUN_ASE) NRO_PROYECTOS,
       TO_CHAR(SUM(HONORARIO), '$99G999G999') TOTAL_HONORARIOS,
       TO_CHAR(SUM(HONORARIO * 0.07), '$99G999G999') "MONTO PAGO ASESOR",
       TO_CHAR(SUM(HONORARIO * 0.93), '$99G999G999') "RECAUDACION DOLPHIN"
FROM ASESOR ASE
JOIN PROFESION PR
  ON ASE.COD_PROFESION = PR.COD_PROFESION
JOIN AFP AF
  ON ASE.COD_AFP = AF.COD_AFP
FULL JOIN PROYECTO PY
  ON PY.NUMRUN_ASE = ASE.NUMRUN_ASE
WHERE EXTRACT(YEAR FROM INICIO_PROYECTO) = EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY TO_CHAR(ASE.NUMRUN_ASE, '00G000G000')||'-'||DVRUN_ASE, APPATERNO||' '||SUBSTR(APMATERNO, 1, 1)||'. '||NOMBRE, TO_CHAR(SUELDO, '$9G999G999'), NOMBRE_PROFESION, NOMBRE_AFP
HAVING COUNT(ASE.NUMRUN_ASE) > 10
ORDER BY NRO_PROYECTOS DESC;


-- CREACION Y CONFIGURACION DEL USUARIO 3
DROP USER VICENTE_CON CASCADE;

CREATE USER VICENTE_CON IDENTIFIED BY DUOC;
ALTER USER VICENTE_CON DEFAULT TABLESPACE USERS;
ALTER USER VICENTE_CON TEMPORARY TABLESPACE TEMP;
ALTER USER VICENTE_CON QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO VICENTE_CON;
GRANT SELECT ON HENRIQUEZ_DEV.V_PAGOS_ASESOR TO VICENTE_CON;

CREATE OR REPLACE SYNONYM VICENTE_CON.SYN_V_PAGOSASESOR
                     FOR HENRIQUEZ_DEV.V_PAGOS_ASESOR;
                     
-- TEST DE USO                     
SELECT *
FROM SYN_V_PAGOSASESOR;

-- CREACION DEL PERFIL PERFIL_DOLPHIN
CREATE PROFILE PERFIL_DOLPHIN LIMIT
   SESSIONS_PER_USER 3
   CONNECT_TIME 2
   FAILED_LOGIN_ATTEMPTS 2;

-- CREACION Y CONFIGURACION DEL ROL ROL_DOLPHIN
CREATE ROLE ROL_DOLPHIN;
GRANT CREATE SESSION TO ROL_DOLPHIN;
GRANT CREATE ANY PROCEDURE TO ROL_DOLPHIN;
GRANT CREATE ANY JOB TO ROL_DOLPHIN;
GRANT SELECT ON OYARZUN_DB.COMUNA TO ROL_DOLPHIN;
GRANT SELECT ON OYARZUN_DB.EMPRESA TO ROL_DOLPHIN;
GRANT UPDATE, INSERT, DELETE ON OYARZUN_DB.TIPO_CONTRATO TO ROL_DOLPHIN;
GRANT UPDATE, INSERT, DELETE ON OYARZUN_DB.SECTOR TO ROL_DOLPHIN;

CREATE OR REPLACE PUBLIC SYNONYM COMUNA FOR OYARZUN_DB.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM EMPRESA FOR OYARZUN_DB.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM TIPO_CONTRATO FOR OYARZUN_DB.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM SECTOR FOR OYARZUN_DB.SECTOR;


-- CREACION Y CONFIGURACION DEL USUARIO 
DROP USER ADM_21802113 CASCADE;

CREATE USER ADM_21802113 IDENTIFIED BY DUOC;
ALTER USER ADM_21802113 DEFAULT TABLESPACE USERS;
ALTER USER ADM_21802113 TEMPORARY TABLESPACE TEMP;
ALTER USER ADM_21802113 QUOTA UNLIMITED ON USERS;
GRANT ROL_DOLPHIN TO ADM_21802113;


-- CONSULTA 1 CON PROBLEMAS
SELECT TO_CHAR(SYSDATE, 'MMYYYY') MES_PROCESO, ASE.NUMRUN_ASE, ASE.DVRUN_ASE,
       ASE.APPATERNO||' '||ASE.APMATERNO||' '||ASE.NOMBRE NOMBRE_ASESOR,
       PR.NOMBRE_PROFESION,
       COUNT(P.NUMRUN_ASE) PROYECTOS,
       SUM(P.HONORARIO) TOTAL_HONORARIOS
FROM ASESOR ASE JOIN PROYECTO P ON ASE.NUMRUN_ASE = P.NUMRUN_ASE
JOIN PROFESION PR ON PR.COD_PROFESION = ASE.COD_PROFESION
WHERE ASE.COD_PROFESION = 3
GROUP BY ASE.NUMRUN_ASE, ASE.DVRUN_ASE, ASE.NOMBRE, ASE.APPATERNO, ASE.APMATERNO, PR.NOMBRE_PROFESION;

-- CREACION DE INDEX
DROP INDEX IDX_ASESOR_PROFESION;
CREATE INDEX IDX_ASESOR_PROFESION ON ASESOR (COD_PROFESION);

-- CONSULTA 2 CON PROBLEMAS
SELECT TO_CHAR(ASE.NUMRUN_ASE, '09G999G999')||'-'||ASE.DVRUN_ASE RUN_ASESOR,
       ASE.APPATERNO||' '||SUBSTR(ASE.APMATERNO, 1, 1)||'.'||UPPER(ASE.NOMBRE) NOMBRE_ASESOR,
       TO_CHAR(ASE.SUELDO, '$9G999G999') SUELDO_ASESOR,
       PR.NOMBRE_PROFESION PROFESION,
       NVL(AFP.NOMBRE_AFP, 'No declara AFP') AFP,
       TO_CHAR(ROUND(ASE.SUELDO * 0.35), '$9G999G999') BONO
FROM ASESOR ASE JOIN AFP ON AFP.COD_AFP = ASE.COD_AFP
JOIN PROFESION PR ON PR.COD_PROFESION = ASE.COD_PROFESION
WHERE ROUND(ASE.SUELDO * 0.35) > 450000;

-- CREACION DE INDEX
DROP INDEX IDX_BONO_ASESOR;
CREATE INDEX IDX_BONO_ASESOR ON ASESOR ( ROUND(sueldo * 0.35) );