-- CASO 1
SELECT TO_CHAR(TO_DATE(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/RR'), 'DD/MM/YYYY') FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = &YEAR
ORDER BY TO_DATE(FECHA_ENTREGA_PROPIEDAD);

SELECT TO_CHAR(TO_DATE(FECINI_ARRIENDO, 'DD/MM/RR'), 'DD/MM/YYYY') FECINI_ARRIENDO
FROM PROPIEDAD_ARRENDADA
WHERE EXTRACT(YEAR FROM FECINI_ARRIENDO) = &YEAR
ORDER BY TO_DATE(FECINI_ARRIENDO);

-- CASO 2
SELECT NUMRUT_CLI||'-'||DVRUT_CLI "RUT CLIENTE",
       NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI "NOMBRE CLIENTE",
       RENTA_CLI RENTA,
       FONOFIJO_CLI "TELEFONO FIJO",
       CELULAR_CLI CELULAR
FROM CLIENTE
WHERE ID_ESTCIVIL = 1
  OR (ID_ESTCIVIL in (3, 4) 
  AND RENTA_CLI >= 800000)
ORDER BY APPATERNO_CLI, NOMBRE_CLI;

-- CASO 3
UNDEFINE PERCENT;
SELECT NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP "SUELDO ACTUAL",
       SUELDO_EMP * (&&PERCENT * 0.01 + 1) "SUELDO REAJUSTADO",
       SUELDO_EMP * (&PERCENT * 0.01) AUMENTO
FROM EMPLEADO
ORDER BY AUMENTO DESC;

UNDEFINE PERCENT;
SELECT NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP "SUELDO ACTUAL",
       SUELDO_EMP * (&&PERCENT * 0.01 + 1) "SUELDO REAJUSTADO",
       SUELDO_EMP * (&PERCENT * 0.01) AUMENTO
FROM EMPLEADO
WHERE SUELDO_EMP >= &MIN
  AND SUELDO_EMP <= &MAX
ORDER BY AUMENTO DESC;

-- CASO 4
SELECT NUMRUT_EMP||'-'||DVRUT_EMP "RUT EMPLEADO",
       NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP "SALARIO ACTUAL",
       SUELDO_EMP * &PERCENT * 0.01 "BONIFICACION EXTRA"
FROM EMPLEADO
WHERE SUELDO_EMP <= 500000
  AND ID_CATEGORIA_EMP != 3
ORDER BY APPATERNO_EMP;

-- CASO 5
DROP TABLE DET_PROPIEDADES_ARRIENDO_VENTA;
CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA AS
SELECT NRO_PROPIEDAD "NUMERO PROPIEDAD",
       TO_CHAR(TO_DATE(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/RR'), 'DD/MM/YYYY') "FECHA ENTREGA PROPIEDAD",
       DIRECCION_PROPIEDAD DIRECCIO,
       SUPERFICIE,
       NRO_DORMITORIOS "CANTIDAD DE DORMITORIOS",
       NRO_BANOS "CANTIDAD DE BAÑOS",
       VALOR_ARRIENDO "VALOR DEL ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = &YEAR
ORDER BY TO_DATE(FECHA_ENTREGA_PROPIEDAD);

DROP TABLE DET_PROPIEDADES_ARRIENDO_VENTA;
CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA AS
SELECT NRO_PROPIEDAD "NUMERO PROPIEDAD",
       TO_CHAR(TO_DATE(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/RR'), 'DD/MM/YYYY') "FECHA ENTREGA PROPIEDAD",
       DIRECCION_PROPIEDAD DIRECCIO,
       SUPERFICIE,
       NRO_DORMITORIOS "CANTIDAD DE DORMITORIOS",
       NRO_BANOS "CANTIDAD DE BAÑOS",
       VALOR_ARRIENDO "VALOR DEL ARRIENDO"
FROM PROPIEDAD
WHERE EXTRACT(MONTH FROM FECHA_ENTREGA_PROPIEDAD) = &MONTH
  AND EXTRACT(YEAR FROM FECHA_ENTREGA_PROPIEDAD) = &YEAR
ORDER BY TO_DATE(FECHA_ENTREGA_PROPIEDAD);