-- CASO 1
SELECT 'El empleado '||NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP||' nació el '||TO_CHAR(TO_DATE(FECNAC_EMP, 'DD/MM/RR'), 'DD/MM/YYYY') "LISTADO DE CUMPLEAÑOS"
FROM empleado
ORDER BY FECNAC_EMP, APPATERNO_EMP;

-- CASO 2
SELECT NUMRUT_CLI "NUMERO RUT",
       DVRUT_CLI "DIGITO VERIFICADOR",
       APPATERNO_CLI||' '||APMATERNO_CLI||' '||NOMBRE_CLI "NOMBRE CLIENTE",
       RENTA_CLI RENTA,
       FONOFIJO_CLI "TELEFONO FIJO",
       CELULAR_CLI CELULAR
FROM cliente
ORDER BY APPATERNO_CLI, APMATERNO_CLI;

-- CASO 3
SELECT NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP SUELDO,
       SUELDO_EMP * 0.5 BONO
FROM empleado
ORDER BY BONO DESC;

-- CASO 4
SELECT NRO_PROPIEDAD "NRO PROPIEDAD",
       NUMRUT_PROP "RUT PROPIETARIO",
       DIRECCION_PROPIEDAD "DIRECCIÓN",
       VALOR_ARRIENDO "VALOR ARRIENDO",
       VALOR_ARRIENDO * 0.054 "VALOR COMPENSACION"
FROM propiedad
ORDER BY NUMRUT_PROP;

-- CASO 5 -
SELECT NUMRUT_EMP||'-'||DVRUT_EMP "RUN EMPLEADO",
       NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP "SALARIO ACTUAL",
       SUELDO_EMP * 1.135 "SALARIO REAJUSTADO",
       SUELDO_EMP * 0.135 REAJUSTE
FROM empleado
ORDER BY REAJUSTE DESC, APPATERNO_EMP;

-- CASO 6
SELECT NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP "NOMBRE EMPLEADO",
       SUELDO_EMP SALARIO,
       SUELDO_EMP * 0.055 COLACION,
       SUELDO_EMP * 0.178 MOVILIZACION,
       SUELDO_EMP * 0.078 SALUD,
       SUELDO_EMP * 0.065 AFP,
       (SUELDO_EMP * 1.233) - (SUELDO_EMP * 0.143) "ALCANCE LÍQUIDO"
FROM empleado
ORDER BY APPATERNO_EMP;