-- Caso 1
SELECT ID_PRODUCTO ID,
       UPPER(NOM_PRODUCTO) NOMBRE_PRODUCTO,
       NVL(CRIANZA, 'No aplica') CRIANZA,
       ID_CEPA CEPA,
       TO_CHAR(PRECIO, '$9G999G999') PRECIO_ACTUAL,
       CASE WHEN STOCK < 40 THEN TO_CHAR(PRECIO*0.7, '$9G999G999')
            WHEN STOCK BETWEEN 40 AND 59 THEN TO_CHAR(PRECIO*0.4, '$9G999G999')
            WHEN STOCK BETWEEN 60 AND 89 THEN TO_CHAR(PRECIO*0.45, '$9G999G999')
            ELSE TO_CHAR(PRECIO*0.5, '$9G999G999') END PRECIO_REBAJA
FROM PRODUCTO
WHERE ID_CEPA = 1
   OR ID_CEPA = 3 AND ID_PRODUCTOR BETWEEN 5 AND 6
ORDER BY NOMBRE_PRODUCTO;

-- Caso 2
SELECT TO_CHAR(SUBSTR(RUNEMPLEADO, 1, LENGTH(RUNEMPLEADO)-1), '00G000G000')||'-'||SUBSTR(RUNEMPLEADO, -1) "RUN EMPLEADO",
       NOMBREEMP||' '||PATERNOEMP||' '||MATERNOEMP "NOMBRE EMPLEADO",
       PATERNOEMP||'.'||SUBSTR(NOMBREEMP, 1, 2) "NOMBRE DE USUARIO",
       LOWER(SUBSTR(NOMBREEMP, 1, 3))||SUBSTR(RUNEMPLEADO, -3, 2)||'$'||INITCAP(SUBSTR(MATERNOEMP, -3))||SUBSTR(FECHA_NAC, 1, 2) CONTRA,
       TRUNC(ADD_MONTHS(SYSDATE, 5), 'MONTH')-4 "FECHA DE REGISTRO"
FROM EMPLEADO
WHERE ID_SUC IN (101, 103)
ORDER BY PATERNOEMP;

-- Caso 3 

UNDEFINE FECHA;
SELECT ID_PEDIDO "Nro. PEDIDO",
       FEC_PEDIDO,
       SUBTOTAL,
       SUBTOTAL*0.19 IVA,
       SUBTOTAL*1.19 TOTAL,
       TO_CHAR(SUBSTR(RUT_CLIENTE, 1, LENGTH(RUT_CLIENTE)-1), '00G000G000')||'-'||SUBSTR(RUT_CLIENTE, -1) "RUN CLIENTE",
       NVL(RUT_DEST, RUT_CLIENTE)
FROM PEDIDO
WHERE TOTAL <= 200000
    --TO_CHAR('&&FECHA', 'MM') - 1 = EXTRACT(MONTH FROM FEC_PEDIDO)
  AND EXTRACT(MONTH FROM ADD_MONTHS(TO_DATE('&&FECHA', 'DD/MM/YYYY'), -1)) = EXTRACT(MONTH FROM FEC_PEDIDO)
    --TO_CHAR('&&FECHA', YYYY) = EXTRACT(YEAR FROM FEC_PEDIDO)
  AND EXTRACT(YEAR FROM TO_DATE('&&FECHA', 'DD/MM/YYYY')) = EXTRACT(YEAR FROM FEC_PEDIDO)
ORDER BY RUT_CLIENTE DESC;